name: run-fusesoc-targets
on: [push]

jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: ultraembedded:core:usb_cdc
          target: sky130
          tool: openlane

  lint-verilator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Lint with Verilator
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: ultraembedded:core:usb_cdc
          target: lint
          tool: verilator
